### ISSUE TITLE
Baffling Crash on Startup

### ISSUE THREAD

**Issue by DoctorPortal** [FelisDiligens/Fallout76-QuickConfiguration#10]
I want to preface this by saying that the program was functioning perfectly as of yesterday (from time of writing). While I had the progra, open, my computer softlocked and I had to hard reboot it, but to my knowledge the program was merely sitting idle. From the moment my computer restarted to now, any time I try and launch the program I receive this error message:

```
Operating system:  Windows 10 64-bit
Program version:   1.9.5
User agent:        Fo76QuickConfiguration/1.9.5 (Windows NT 10.0.22000.0; x64) .NETFramework/4.7.2
Running as admin:  No
Game edition:      Unknown
System locale:     en-US
App locale:        en-US
************** Stack trace **************
If any files are listed (like "D:\Workspace\...\*.cs:line 123"):
Those are files on *my* computer, so don't worry if you can't find them.

System.Xml.XmlException: '.', hexadecimal value 0x00, is an invalid character. Line 1, position 1.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowInvalidChar(Char[] data, Int32 length, Int32 invCharPos)
   at System.Xml.XmlTextReaderImpl.ParseRootLevelWhitespace()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
   at Fo76ini.Profiles.ProfileManager.Load() in D:\Workspace\Fallout 76 Quick Configuration\Fallout76-QuickConfiguration\Fo76ini\Profiles\ProfileManager.cs:line 116
   at Fo76ini.Form1.Form1_Load(Object sender, EventArgs e) in D:\Workspace\Fallout 76 Quick Configuration\Fallout76-QuickConfiguration\Fo76ini\Forms\Form1\Form1.cs:line 324
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

```

I've tried reinstalling the program, I've tried reinstalling .NET Framework (which doesn't actually work as the program merely says "it's already installed", so nothing happens), I've tried numerous things, and to zero effect. I really want this program to work as I have yet to get any other method of mod installation to work.

**Comment by FelisDiligens** [comment]
This issue should be fixed in v1.12.3 now.
