### ISSUE TITLE
NullReferenceException after 1.12.5 update

### ISSUE THREAD

**Issue by Sondju** [FelisDiligens/Fallout76-QuickConfiguration#20]
*************** Error message ***************
System.NullReferenceException: Object reference not set to an instance of an object.

**************** System Info ****************
Operating system:  Windows 10 64-bit
Program version:   1.12.5
User agent:        Fo76QuickConfiguration/1.12.5 (Windows NT 10.0.17763.0; x64) .NETFramework/4.7.2
Running as admin:  No
System culture:    Russian (Russia)
App locale:        en-US
Game edition:      Steam

**************** Stack Trace ****************
If any files are listed (like "at ... in ...\*.cs:line 123"):
Those are files on *my* computer, so don't worry if you can't find them.

System.NullReferenceException: Object reference not set to an instance of an object.
   at Fo76ini.Interface.Theming.DetectSystemTheme() in D:\Workspace\Fallout76-QuickConfiguration\Fo76ini\Interface\Theming.cs:line 72
   at Fo76ini.FormMods..ctor() in D:\Workspace\Fallout76-QuickConfiguration\Fo76ini\Forms\FormMods\FormMods.cs:line 71
   at Fo76ini.FormMain..ctor() in D:\Workspace\Fallout76-QuickConfiguration\Fo76ini\Forms\FormMain\FormMain.cs:line 30
   at Fo76ini.Program.Main() in D:\Workspace\Fallout76-QuickConfiguration\Fo76ini\Program.cs:line 56

**Comment by FelisDiligens** [comment]
Well... that's embarrasing. 🙈
Should be fixed now.
