### ISSUE TITLE
System.OutOfMemoryException

### ISSUE THREAD

**Issue by TimurSl** [FelisDiligens/Fallout76-QuickConfiguration#22]
`*************** Error message ***************
System.OutOfMemoryException: Недостаточно памяти.

**************** System Info ****************
Operating system:  Windows 10 64-bit
Program version:   1.12.6
User agent:        Fo76QuickConfiguration/1.12.6 (Windows NT 10.0.19045.0; x64) .NETFramework/4.7.2
Running as admin:  No
System culture:    Russian (Russia)
App locale:        ru-RU
Game edition:      Steam

**************** Stack Trace ****************
If any files are listed (like "at ... in ...\*.cs:line 123"):
Those are files on *my* computer, so don't worry if you can't find them.

System.OutOfMemoryException:
   at System.Drawing.Image.FromFile(String filename, Boolean useEmbeddedColorManagement)
   at Fo76ini.Forms.FormMain.Tabs.UserControlNexusMods.RefreshNMUI() in C:\Users\vboxuser\Downloads\Fallout76-QuickConfiguration\Fo76ini\Forms\FormMain\Views\UserControlNexusMods.cs:line 172
   at Fo76ini.Forms.FormMain.Tabs.UserControlNexusMods.UserControlNexusMods_Load(Object sender, EventArgs e) in C:\Users\vboxuser\Downloads\Fallout76-QuickConfiguration\Fo76ini\Forms\FormMain\Views\UserControlNexusMods.cs:line 58
   at System.Windows.Forms.UserControl.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.SetVisibleCore(Boolean value)
   at Fo76ini.Controls.ViewControl.OpenView(UserControl view) in C:\Users\vboxuser\Downloads\Fallout76-QuickConfiguration\Fo76ini\Controls\ViewControl.cs:line 107
   at Fo76ini.Forms.FormMain.UserControlSideNav.buttonNexusMods_Click(Object sender, EventArgs e) in C:\Users\vboxuser\Downloads\Fallout76-QuickConfiguration\Fo76ini\Forms\FormMain\UserControlSideNav.cs:line 210
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
`

Steps to reproduce:
1. Go to Nexus tab
2. Login with Nexus account
3. Reopen Nexus tab

**Comment by thomasgraham18** [comment]
Fixed here:

https://github.com/thomasgraham18/Fallout76-QuickConfiguration/releases/tag/quickfix

**Comment by FelisDiligens** [comment]
Fixed in v1.12.7.
